#!/bin/python3

import math
import os
import random
import re
import sys

def miniMaxSum(arr):
    final = [sum(arr)-x for x in arr]
    print(min(final), max(final))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
##############################################################3
#!/bin/python3

import math
import os
import random
import re
import sys

def miniMaxSum(arr):
    arr = sorted(arr)
    print(sum(arr[0:4]), sum(arr[1:5]))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
